/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * This machine's identity: a keypair whose private half never leaves the
 * security hardware. Obtain via {@link ensureDeviceId}.
 */
export declare class DeviceId {
  /**
   * The device ID: `SHA256:<base64>` fingerprint of the public key
   * (SPKI DER), following the SSH fingerprint convention. Stable for the
   * lifetime of the key; survives re-installs while the handle persists.
   */
  get id(): string
  /** The public key as SPKI PEM, for enrolling this device with a server. */
  get publicKeyPem(): string
  /**
   * Where the private key lives. `hardware` means it cannot be extracted
   * from this machine (Secure Enclave / TPM); `software` means it is
   * encrypted at rest but usable if copied along with its OS keyring.
   */
  get protection(): string
  /**
   * Prove possession of the device key: ECDSA P-256 signature over
   * `payload` (SHA-256 applied internally), returned as base64url-encoded
   * P1363 (`r || s`) — verifiable with WebCrypto as-is.
   */
  sign(payload: string): string
}

export interface DeviceIdOptions {
  /**
   * Directory where the hardware-wrapped key handle is persisted.
   * Defaults to the platform key-storage location.
   */
  dir?: string
  /**
   * Namespace for the key in platform key storage (keychain service name
   * on macOS). Defaults to "deviceid".
   */
  appName?: string
  /** Key label within the namespace. Defaults to "device". */
  label?: string
}

/**
 * Ensure this machine has a device identity: load the existing key or
 * generate one in the security hardware. Idempotent — the same installation
 * always resolves to the same key, and therefore the same {@link DeviceId#id}.
 *
 * Fail-closed: on machines with no usable backend (Windows without a TPM,
 * Linux without a Secret Service) this throws instead of silently
 * downgrading — pair it with your own software fallback if you need one.
 */
export declare function ensureDeviceId(options?: DeviceIdOptions | undefined | null): DeviceId
